#!/usr/bin/env ts-node

/**
 * AI Content Generator Script
 *
 * This script generates themed word problem templates for math modules.
 * It demonstrates the content injection architecture by creating new
 * templates.json content based on a theme.
 *
 * Usage:
 *   npx ts-node scripts/generate-content.ts --theme "Pirates"
 *   npx ts-node scripts/generate-content.ts --theme "Space"
 *   npx ts-node scripts/generate-content.ts --theme "Dinosaurs"
 */

import * as fs from 'fs';
import * as path from 'path';

// Theme templates - in production, this would be generated by an LLM
const themeTemplates: Record<string, any> = {
  Pirates: {
    division: {
      wordProblems: {
        he: [
          {
            text: "לקפטן יש {total} מטבעות זהב. הוא רוצה לחלק אותן שווה ל-{groups} שודדי ים. כמה מטבעות יקבל כל שודד?",
            vars: ["total", "groups"]
          },
          {
            text: "יש {total} תותחים על {groups} ספינות. כמה תותחים בממוצע על כל ספינה?",
            vars: ["total", "groups"]
          },
          {
            text: "הקפטן מצא {total} פנינים ב-{groups} תיבות אוצר. כמה פנינים בכל תיבה אם מחלקים שווה?",
            vars: ["total", "groups"]
          }
        ],
        en: [
          {
            text: "The captain has {total} gold coins. He wants to divide them equally among {groups} pirates. How many coins will each pirate get?",
            vars: ["total", "groups"]
          },
          {
            text: "There are {total} cannons on {groups} ships. How many cannons on average per ship?",
            vars: ["total", "groups"]
          },
          {
            text: "The captain found {total} pearls in {groups} treasure chests. How many pearls per chest if divided equally?",
            vars: ["total", "groups"]
          }
        ]
      }
    },
    multiplication: {
      wordProblems: {
        he: [
          {
            text: "לקפטן יש {groups} ספינות, ובכל ספינה {items} שודדי ים. כמה שודדים יש לו בסך הכל?",
            vars: ["groups", "items"]
          },
          {
            text: "בכל תיבת אוצר יש {items} מטבעות זהב. אם יש {groups} תיבות, כמה מטבעות יש בסך הכל?",
            vars: ["items", "groups"]
          },
          {
            text: "הקפטן מפליג {items} שעות בכל יום. כמה שעות הוא יפליג ב-{groups} ימים?",
            vars: ["items", "groups"]
          }
        ],
        en: [
          {
            text: "The captain has {groups} ships, and each ship has {items} pirates. How many pirates does he have in total?",
            vars: ["groups", "items"]
          },
          {
            text: "Each treasure chest has {items} gold coins. If there are {groups} chests, how many coins in total?",
            vars: ["items", "groups"]
          },
          {
            text: "The captain sails {items} hours every day. How many hours will he sail in {groups} days?",
            vars: ["items", "groups"]
          }
        ]
      }
    },
    fraction: {
      wordProblems: {
        he: [
          {
            text: "לקפטן יש מפת אוצר. הוא חקר {numerator}/{denominator} מהמפה. איזה חלק נשאר?",
            vars: ["numerator", "denominator"]
          },
          {
            text: "בצוות יש {total} שודדי ים. {numerator}/{denominator} מהם יודעים לשחות. כמה שודדים יודעים לשחות?",
            vars: ["total", "numerator", "denominator"]
          }
        ],
        en: [
          {
            text: "The captain has a treasure map. He explored {numerator}/{denominator} of the map. What fraction is left?",
            vars: ["numerator", "denominator"]
          },
          {
            text: "The crew has {total} pirates. {numerator}/{denominator} of them can swim. How many pirates can swim?",
            vars: ["total", "numerator", "denominator"]
          }
        ]
      }
    },
    decimal: {
      wordProblems: {
        he: [
          {
            text: "לקפטן יש {whole}.{decimal} קילוגרם זהב. כמה גרם זה?",
            vars: ["whole", "decimal"]
          },
          {
            text: "המרחק לאי האוצר הוא {whole}.{decimal} מיילים ימיים. כמה זה במטרים?",
            vars: ["whole", "decimal"]
          }
        ],
        en: [
          {
            text: "The captain has {whole}.{decimal} kilograms of gold. How many grams is that?",
            vars: ["whole", "decimal"]
          },
          {
            text: "The distance to Treasure Island is {whole}.{decimal} nautical miles. How many meters is that?",
            vars: ["whole", "decimal"]
          }
        ]
      }
    },
    distributive: {
      wordProblems: {
        he: [
          {
            text: "הקפטן קנה {groups} תיבות. בכל תיבה יש {items1} מטבעות זהב ו-{items2} פנינים. כמה אוצרות קנה בסך הכל?",
            vars: ["groups", "items1", "items2"]
          }
        ],
        en: [
          {
            text: "The captain bought {groups} chests. Each chest has {items1} gold coins and {items2} pearls. How many treasures did he buy in total?",
            vars: ["groups", "items1", "items2"]
          }
        ]
      }
    },
    "number-line": {
      wordProblems: {
        he: [
          {
            text: "הספינה עומדת על המיקום {start} בים. היא מפליגה {steps} קשרים קדימה. לאיזה מיקום תגיע?",
            vars: ["start", "steps"]
          },
          {
            text: "יש אי על המיקום {position}. איפה האי על המפה?",
            vars: ["position"]
          }
        ],
        en: [
          {
            text: "The ship is at position {start} at sea. It sails {steps} knots forward. What position will it reach?",
            vars: ["start", "steps"]
          },
          {
            text: "There is an island at position {position}. Where is the island on the map?",
            vars: ["position"]
          }
        ]
      }
    },
    "order-operations": {
      wordProblems: {
        he: [
          {
            text: "הקפטן קנה {num1} מפות ב-{num2} שקלים כל אחת, ועוד {num3} משקפות. כמה שילם בסך הכל?",
            vars: ["num1", "num2", "num3"]
          }
        ],
        en: [
          {
            text: "The captain bought {num1} maps for {num2} dollars each, and {num3} more telescopes. How much did he pay in total?",
            vars: ["num1", "num2", "num3"]
          }
        ]
      }
    }
  },
  Space: {
    division: {
      wordProblems: {
        he: [
          {
            text: "לאמה יש {total} כוכבים בגלקסיה. היא רוצה לחלק אותם שווה ל-{groups} מערכות שמש. כמה כוכבים בכל מערכת?",
            vars: ["total", "groups"]
          },
          {
            text: "יש {total} אסטרונאוטים ו-{groups} חלליות. כמה אסטרונאוטים בכל חללית אם נחלק שווה?",
            vars: ["total", "groups"]
          },
          {
            text: "החללית עברה {total} שנות אור ב-{groups} ימים. כמה שנות אור ביום בממוצע?",
            vars: ["total", "groups"]
          }
        ],
        en: [
          {
            text: "Emma has {total} stars in the galaxy. She wants to divide them equally into {groups} solar systems. How many stars per system?",
            vars: ["total", "groups"]
          },
          {
            text: "There are {total} astronauts and {groups} spaceships. How many astronauts per spaceship if divided equally?",
            vars: ["total", "groups"]
          },
          {
            text: "The spaceship traveled {total} light years in {groups} days. How many light years per day on average?",
            vars: ["total", "groups"]
          }
        ]
      }
    },
    multiplication: {
      wordProblems: {
        he: [
          {
            text: "לאמה יש {groups} כוכבי לכת, ובכל כוכב {items} ירחים. כמה ירחים יש לה בסך הכל?",
            vars: ["groups", "items"]
          },
          {
            text: "בכל חללית יש {items} אסטרונאוטים. אם יש {groups} חלליות, כמה אסטרונאוטים יש בסך הכל?",
            vars: ["items", "groups"]
          },
          {
            text: "אמה רואה {items} כוכבים בכל לילה. כמה כוכבים היא תראה ב-{groups} לילות?",
            vars: ["items", "groups"]
          }
        ],
        en: [
          {
            text: "Emma has {groups} planets, and each planet has {items} moons. How many moons does she have in total?",
            vars: ["groups", "items"]
          },
          {
            text: "Each spaceship has {items} astronauts. If there are {groups} spaceships, how many astronauts in total?",
            vars: ["items", "groups"]
          },
          {
            text: "Emma sees {items} stars every night. How many stars will she see in {groups} nights?",
            vars: ["items", "groups"]
          }
        ]
      }
    },
    fraction: {
      wordProblems: {
        he: [
          {
            text: "לאמה יש טלסקופ. היא סרקה {numerator}/{denominator} מהשמיים. איזה חלק נשאר?",
            vars: ["numerator", "denominator"]
          },
          {
            text: "בתחנת החלל יש {total} אסטרונאוטים. {numerator}/{denominator} מהם יודעים לטוס. כמה אסטרונאוטים יודעים לטוס?",
            vars: ["total", "numerator", "denominator"]
          }
        ],
        en: [
          {
            text: "Emma has a telescope. She scanned {numerator}/{denominator} of the sky. What fraction is left?",
            vars: ["numerator", "denominator"]
          },
          {
            text: "There are {total} astronauts at the space station. {numerator}/{denominator} of them can fly. How many astronauts can fly?",
            vars: ["total", "numerator", "denominator"]
          }
        ]
      }
    },
    decimal: {
      wordProblems: {
        he: [
          {
            text: "לאמה יש {whole}.{decimal} קילוגרם מטאוריטים. כמה גרם זה?",
            vars: ["whole", "decimal"]
          },
          {
            text: "המרחק לירח הוא {whole}.{decimal} מיליון קילומטרים. כמה זה במטרים?",
            vars: ["whole", "decimal"]
          }
        ],
        en: [
          {
            text: "Emma has {whole}.{decimal} kilograms of meteorites. How many grams is that?",
            vars: ["whole", "decimal"]
          },
          {
            text: "The distance to the moon is {whole}.{decimal} million kilometers. How many meters is that?",
            vars: ["whole", "decimal"]
          }
        ]
      }
    },
    distributive: {
      wordProblems: {
        he: [
          {
            text: "אמה קנתה {groups} חבילות. בכל חבילה יש {items1} מטאוריטים ו-{items2} אבני חלל. כמה פריטים קנתה בסך הכל?",
            vars: ["groups", "items1", "items2"]
          }
        ],
        en: [
          {
            text: "Emma bought {groups} packages. Each package has {items1} meteorites and {items2} space rocks. How many items did she buy in total?",
            vars: ["groups", "items1", "items2"]
          }
        ]
      }
    },
    "number-line": {
      wordProblems: {
        he: [
          {
            text: "החללית עומדת על נקודה {start} במסלול. היא מתקדמת {steps} נקודות קדימה. לאיזו נקודה תגיע?",
            vars: ["start", "steps"]
          },
          {
            text: "יש כוכב על נקודה {position}. איפה הכוכב על המפה?",
            vars: ["position"]
          }
        ],
        en: [
          {
            text: "The spaceship is at point {start} in orbit. It advances {steps} points forward. What point will it reach?",
            vars: ["start", "steps"]
          },
          {
            text: "There is a star at point {position}. Where is the star on the map?",
            vars: ["position"]
          }
        ]
      }
    },
    "order-operations": {
      wordProblems: {
        he: [
          {
            text: "אמה קנתה {num1} חליפות חלל ב-{num2} שקלים כל אחת, ועוד {num3} קסדות. כמה שילמה בסך הכל?",
            vars: ["num1", "num2", "num3"]
          }
        ],
        en: [
          {
            text: "Emma bought {num1} spacesuits for {num2} dollars each, and {num3} more helmets. How much did she pay in total?",
            vars: ["num1", "num2", "num3"]
          }
        ]
      }
    }
  }
};

/**
 * Parse command line arguments
 */
function parseArgs(): { theme: string } {
  const args = process.argv.slice(2);
  let theme = 'Pirates'; // Default theme

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--theme' && args[i + 1]) {
      theme = args[i + 1];
      i++;
    }
  }

  return { theme };
}

/**
 * Generate content using AI (mocked for now)
 *
 * In production, this would call an LLM API like:
 * - OpenAI GPT-4
 * - Anthropic Claude
 * - Google Gemini
 *
 * Prompt example:
 * "Generate Hebrew and English word problem templates for math modules
 *  with a {theme} theme. Include division, multiplication, fraction, etc.
 *  Use placeholders like {total}, {groups}, {items} for variables."
 */
async function generateWithAI(theme: string): Promise<any> {
  console.log(`\n🤖 [AI Generator] Generating content for theme: "${theme}"`);
  console.log('📝 [AI Generator] In production, this would call an LLM API...\n');

  // Check if we have a pre-made template for this theme
  if (themeTemplates[theme]) {
    console.log(`✅ [AI Generator] Using pre-generated template for "${theme}"\n`);
    return themeTemplates[theme];
  }

  // If no template exists, show what the LLM prompt would look like
  const llmPrompt = `
You are an AI content generator for a children's math education platform.

Generate word problem templates for math modules with a "${theme}" theme.

Requirements:
- Support both Hebrew (he) and English (en)
- Include templates for: division, multiplication, fraction, decimal, distributive, number-line, order-operations
- Use placeholder variables like {total}, {groups}, {items}, {numerator}, {denominator}, etc.
- Keep problems simple and appropriate for elementary school children
- Make them fun and engaging with the ${theme} theme

Return JSON matching this structure:
{
  "division": {
    "wordProblems": {
      "he": [{ "text": "...", "vars": ["total", "groups"] }],
      "en": [{ "text": "...", "vars": ["total", "groups"] }]
    }
  },
  ...
}
`;

  console.log('🎯 [AI Generator] LLM Prompt that would be sent:');
  console.log('─'.repeat(60));
  console.log(llmPrompt);
  console.log('─'.repeat(60));
  console.log('\n⚠️  [AI Generator] No pre-made template for this theme.');
  console.log('💡 [AI Generator] Available themes: Pirates, Space');
  console.log('🔧 [AI Generator] To add a new theme, integrate an LLM API here.\n');

  throw new Error(`No template available for theme: ${theme}. Use "Pirates" or "Space".`);
}

/**
 * Save content to templates.json
 */
function saveContent(content: any) {
  // Use relative path from current working directory
  const templatesPath = path.join(
    process.cwd(),
    'learningisfun-app',
    'lib',
    'math',
    'content',
    'templates.json'
  );

  console.log(`💾 [Save] Writing to: ${templatesPath}`);

  // Create backup of existing file
  if (fs.existsSync(templatesPath)) {
    const backupPath = templatesPath.replace('.json', '.backup.json');
    fs.copyFileSync(templatesPath, backupPath);
    console.log(`📦 [Backup] Created backup at: ${backupPath}`);
  }

  // Write new content
  fs.writeFileSync(
    templatesPath,
    JSON.stringify(content, null, 2),
    'utf-8'
  );

  console.log(`✅ [Save] Content saved successfully!\n`);
}

/**
 * Main execution
 */
async function main() {
  console.log('🚀 AI Content Generator - Story 15\n');

  try {
    // Parse arguments
    const { theme } = parseArgs();

    // Generate content
    const content = await generateWithAI(theme);

    // Save to file
    saveContent(content);

    console.log('✨ Generation complete!');
    console.log(`🎨 Theme: ${theme}`);
    console.log('📂 Location: learningisfun-app/lib/math/content/templates.json');
    console.log('\n💡 Next steps:');
    console.log('   1. Restart your Next.js dev server (npm run dev)');
    console.log('   2. Test the API: POST /api/math/generate with moduleName="division"');
    console.log('   3. Verify the new themed content appears in questions\n');

  } catch (error) {
    console.error('❌ Error:', error instanceof Error ? error.message : error);
    process.exit(1);
  }
}

// Run the script
main();

export { generateWithAI, saveContent, parseArgs };
